name: Ping Streamlit App

on:
  schedule:
    # Ping hver 30. minut
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app (root + pages)
        run: |
          set -e
          BASE="https://knudsenhomeapp.streamlit.app"
          URLS=(
            "$BASE"
            "$BASE/Shopping"
            "$BASE/Memories"
            "$BASE/Maintenance"
          )

          for URL in "${URLS[@]}"; do
            echo "Pinging $URL"
            curl -L -sS -o /dev/null -w "HTTP %{http_code}\n" "$URL"
          done
